# Sample Config File for star_yuuki_bot
# Please replace setting from `libs/config.py` options

Yuuki:
  Default_Language: en
  Hour_KickLimit: 10
  Hour_CancelLimit: 10
  GroupMebers_Demand: 10
  SecurityService: True

LINE:
  Server:
    Host: https://example.com
    Command_Path: /example_path
    LongPoll_path: /example_path

  Account:
    X-Line-Application: LINE_Application_Identification
    X-Line-Access: LINE_Application_AccessKey
    User-Agent: LINE_Application_User-Agent
