Yuuki:
  Default_Language: en
  Admin:
    -
  KickLimit: 10
  CancelLimit: 10
  GroupMebers_Demand: 10

LINE:
  Server:
    Host:
    Command_Path:
    LongPoll_path:

  Account:
    X-Line-Application:
    X-Line-Access:
    User-Agent:

  helper_LINE_ACCESS_KEYs:
    -
